# Generated by Django 3.0.7 on 2020-06-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200630_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book', 'status', 'due_back']},
        ),
    ]
