# Generated by Django 3.0.7 on 2020-06-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200630_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['id', 'status', 'due_back']},
        ),
    ]
