# Generated by Django 3.0.7 on 2020-07-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['id', 'status', 'due_back'], 'permissions': (('can_mark_returned', 'Return Book'),)},
        ),
    ]
